//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Person {
            get {
                return this.PersonField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonField, value) != true)) {
                    this.PersonField = value;
                    this.RaisePropertyChanged("Person");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AdminStatus {
            get {
                return this.AdminStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminStatusField, value) != true)) {
                    this.AdminStatusField = value;
                    this.RaisePropertyChanged("AdminStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.userServiceSoap")]
    public interface userServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebApplication2.ServiceReference1.HelloWorldResponse HelloWorld(WebApplication2.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.HelloWorldResponse> HelloWorldAsync(WebApplication2.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUser", ReplyAction="*")]
        WebApplication2.ServiceReference1.AddUserResponse AddUser(WebApplication2.ServiceReference1.AddUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUser", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.AddUserResponse> AddUserAsync(WebApplication2.ServiceReference1.AddUserRequest request);
        
        // CODEGEN: Generating message contract since element name userId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUser", ReplyAction="*")]
        WebApplication2.ServiceReference1.UpdateUserResponse UpdateUser(WebApplication2.ServiceReference1.UpdateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.UpdateUserResponse> UpdateUserAsync(WebApplication2.ServiceReference1.UpdateUserRequest request);
        
        // CODEGEN: Generating message contract since element name userId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteUser", ReplyAction="*")]
        WebApplication2.ServiceReference1.DeleteUserResponse DeleteUser(WebApplication2.ServiceReference1.DeleteUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteUser", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.DeleteUserResponse> DeleteUserAsync(WebApplication2.ServiceReference1.DeleteUserRequest request);
        
        // CODEGEN: Generating message contract since element name GetUsersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsers", ReplyAction="*")]
        WebApplication2.ServiceReference1.GetUsersResponse GetUsers(WebApplication2.ServiceReference1.GetUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.GetUsersResponse> GetUsersAsync(WebApplication2.ServiceReference1.GetUsersRequest request);
        
        // CODEGEN: Generating message contract since element name GetAdminsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAdmins", ReplyAction="*")]
        WebApplication2.ServiceReference1.GetAdminsResponse GetAdmins(WebApplication2.ServiceReference1.GetAdminsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAdmins", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.GetAdminsResponse> GetAdminsAsync(WebApplication2.ServiceReference1.GetAdminsRequest request);
        
        // CODEGEN: Generating message contract since element name GetRegularUsersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRegularUsers", ReplyAction="*")]
        WebApplication2.ServiceReference1.GetRegularUsersResponse GetRegularUsers(WebApplication2.ServiceReference1.GetRegularUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRegularUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.GetRegularUsersResponse> GetRegularUsersAsync(WebApplication2.ServiceReference1.GetRegularUsersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebApplication2.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebApplication2.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUser", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.AddUserRequestBody Body;
        
        public AddUserRequest() {
        }
        
        public AddUserRequest(WebApplication2.ServiceReference1.AddUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string adminStatus;
        
        public AddUserRequestBody() {
        }
        
        public AddUserRequestBody(string username, string password, string adminStatus) {
            this.username = username;
            this.password = password;
            this.adminStatus = adminStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.AddUserResponseBody Body;
        
        public AddUserResponse() {
        }
        
        public AddUserResponse(WebApplication2.ServiceReference1.AddUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddUserResponseBody {
        
        public AddUserResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUser", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.UpdateUserRequestBody Body;
        
        public UpdateUserRequest() {
        }
        
        public UpdateUserRequest(WebApplication2.ServiceReference1.UpdateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string adminStatus;
        
        public UpdateUserRequestBody() {
        }
        
        public UpdateUserRequestBody(string userId, string username, string password, string adminStatus) {
            this.userId = userId;
            this.username = username;
            this.password = password;
            this.adminStatus = adminStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.UpdateUserResponseBody Body;
        
        public UpdateUserResponse() {
        }
        
        public UpdateUserResponse(WebApplication2.ServiceReference1.UpdateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateUserResponseBody {
        
        public UpdateUserResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteUser", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.DeleteUserRequestBody Body;
        
        public DeleteUserRequest() {
        }
        
        public DeleteUserRequest(WebApplication2.ServiceReference1.DeleteUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        public DeleteUserRequestBody() {
        }
        
        public DeleteUserRequestBody(string userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.DeleteUserResponseBody Body;
        
        public DeleteUserResponse() {
        }
        
        public DeleteUserResponse(WebApplication2.ServiceReference1.DeleteUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteUserResponseBody {
        
        public DeleteUserResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsers", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.GetUsersRequestBody Body;
        
        public GetUsersRequest() {
        }
        
        public GetUsersRequest(WebApplication2.ServiceReference1.GetUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUsersRequestBody {
        
        public GetUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.GetUsersResponseBody Body;
        
        public GetUsersResponse() {
        }
        
        public GetUsersResponse(WebApplication2.ServiceReference1.GetUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication2.ServiceReference1.User[] GetUsersResult;
        
        public GetUsersResponseBody() {
        }
        
        public GetUsersResponseBody(WebApplication2.ServiceReference1.User[] GetUsersResult) {
            this.GetUsersResult = GetUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAdminsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAdmins", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.GetAdminsRequestBody Body;
        
        public GetAdminsRequest() {
        }
        
        public GetAdminsRequest(WebApplication2.ServiceReference1.GetAdminsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAdminsRequestBody {
        
        public GetAdminsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAdminsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAdminsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.GetAdminsResponseBody Body;
        
        public GetAdminsResponse() {
        }
        
        public GetAdminsResponse(WebApplication2.ServiceReference1.GetAdminsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAdminsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication2.ServiceReference1.User[] GetAdminsResult;
        
        public GetAdminsResponseBody() {
        }
        
        public GetAdminsResponseBody(WebApplication2.ServiceReference1.User[] GetAdminsResult) {
            this.GetAdminsResult = GetAdminsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRegularUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRegularUsers", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.GetRegularUsersRequestBody Body;
        
        public GetRegularUsersRequest() {
        }
        
        public GetRegularUsersRequest(WebApplication2.ServiceReference1.GetRegularUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetRegularUsersRequestBody {
        
        public GetRegularUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRegularUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRegularUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.GetRegularUsersResponseBody Body;
        
        public GetRegularUsersResponse() {
        }
        
        public GetRegularUsersResponse(WebApplication2.ServiceReference1.GetRegularUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRegularUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication2.ServiceReference1.User[] GetRegularUsersResult;
        
        public GetRegularUsersResponseBody() {
        }
        
        public GetRegularUsersResponseBody(WebApplication2.ServiceReference1.User[] GetRegularUsersResult) {
            this.GetRegularUsersResult = GetRegularUsersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface userServiceSoapChannel : WebApplication2.ServiceReference1.userServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class userServiceSoapClient : System.ServiceModel.ClientBase<WebApplication2.ServiceReference1.userServiceSoap>, WebApplication2.ServiceReference1.userServiceSoap {
        
        public userServiceSoapClient() {
        }
        
        public userServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public userServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public userServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public userServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.ServiceReference1.HelloWorldResponse WebApplication2.ServiceReference1.userServiceSoap.HelloWorld(WebApplication2.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebApplication2.ServiceReference1.HelloWorldRequest inValue = new WebApplication2.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebApplication2.ServiceReference1.HelloWorldRequestBody();
            WebApplication2.ServiceReference1.HelloWorldResponse retVal = ((WebApplication2.ServiceReference1.userServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.HelloWorldResponse> WebApplication2.ServiceReference1.userServiceSoap.HelloWorldAsync(WebApplication2.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication2.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            WebApplication2.ServiceReference1.HelloWorldRequest inValue = new WebApplication2.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebApplication2.ServiceReference1.HelloWorldRequestBody();
            return ((WebApplication2.ServiceReference1.userServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.ServiceReference1.AddUserResponse WebApplication2.ServiceReference1.userServiceSoap.AddUser(WebApplication2.ServiceReference1.AddUserRequest request) {
            return base.Channel.AddUser(request);
        }
        
        public void AddUser(string username, string password, string adminStatus) {
            WebApplication2.ServiceReference1.AddUserRequest inValue = new WebApplication2.ServiceReference1.AddUserRequest();
            inValue.Body = new WebApplication2.ServiceReference1.AddUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.adminStatus = adminStatus;
            WebApplication2.ServiceReference1.AddUserResponse retVal = ((WebApplication2.ServiceReference1.userServiceSoap)(this)).AddUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.AddUserResponse> WebApplication2.ServiceReference1.userServiceSoap.AddUserAsync(WebApplication2.ServiceReference1.AddUserRequest request) {
            return base.Channel.AddUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication2.ServiceReference1.AddUserResponse> AddUserAsync(string username, string password, string adminStatus) {
            WebApplication2.ServiceReference1.AddUserRequest inValue = new WebApplication2.ServiceReference1.AddUserRequest();
            inValue.Body = new WebApplication2.ServiceReference1.AddUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.adminStatus = adminStatus;
            return ((WebApplication2.ServiceReference1.userServiceSoap)(this)).AddUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.ServiceReference1.UpdateUserResponse WebApplication2.ServiceReference1.userServiceSoap.UpdateUser(WebApplication2.ServiceReference1.UpdateUserRequest request) {
            return base.Channel.UpdateUser(request);
        }
        
        public void UpdateUser(string userId, string username, string password, string adminStatus) {
            WebApplication2.ServiceReference1.UpdateUserRequest inValue = new WebApplication2.ServiceReference1.UpdateUserRequest();
            inValue.Body = new WebApplication2.ServiceReference1.UpdateUserRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.adminStatus = adminStatus;
            WebApplication2.ServiceReference1.UpdateUserResponse retVal = ((WebApplication2.ServiceReference1.userServiceSoap)(this)).UpdateUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.UpdateUserResponse> WebApplication2.ServiceReference1.userServiceSoap.UpdateUserAsync(WebApplication2.ServiceReference1.UpdateUserRequest request) {
            return base.Channel.UpdateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication2.ServiceReference1.UpdateUserResponse> UpdateUserAsync(string userId, string username, string password, string adminStatus) {
            WebApplication2.ServiceReference1.UpdateUserRequest inValue = new WebApplication2.ServiceReference1.UpdateUserRequest();
            inValue.Body = new WebApplication2.ServiceReference1.UpdateUserRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.adminStatus = adminStatus;
            return ((WebApplication2.ServiceReference1.userServiceSoap)(this)).UpdateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.ServiceReference1.DeleteUserResponse WebApplication2.ServiceReference1.userServiceSoap.DeleteUser(WebApplication2.ServiceReference1.DeleteUserRequest request) {
            return base.Channel.DeleteUser(request);
        }
        
        public void DeleteUser(string userId) {
            WebApplication2.ServiceReference1.DeleteUserRequest inValue = new WebApplication2.ServiceReference1.DeleteUserRequest();
            inValue.Body = new WebApplication2.ServiceReference1.DeleteUserRequestBody();
            inValue.Body.userId = userId;
            WebApplication2.ServiceReference1.DeleteUserResponse retVal = ((WebApplication2.ServiceReference1.userServiceSoap)(this)).DeleteUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.DeleteUserResponse> WebApplication2.ServiceReference1.userServiceSoap.DeleteUserAsync(WebApplication2.ServiceReference1.DeleteUserRequest request) {
            return base.Channel.DeleteUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication2.ServiceReference1.DeleteUserResponse> DeleteUserAsync(string userId) {
            WebApplication2.ServiceReference1.DeleteUserRequest inValue = new WebApplication2.ServiceReference1.DeleteUserRequest();
            inValue.Body = new WebApplication2.ServiceReference1.DeleteUserRequestBody();
            inValue.Body.userId = userId;
            return ((WebApplication2.ServiceReference1.userServiceSoap)(this)).DeleteUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.ServiceReference1.GetUsersResponse WebApplication2.ServiceReference1.userServiceSoap.GetUsers(WebApplication2.ServiceReference1.GetUsersRequest request) {
            return base.Channel.GetUsers(request);
        }
        
        public WebApplication2.ServiceReference1.User[] GetUsers() {
            WebApplication2.ServiceReference1.GetUsersRequest inValue = new WebApplication2.ServiceReference1.GetUsersRequest();
            inValue.Body = new WebApplication2.ServiceReference1.GetUsersRequestBody();
            WebApplication2.ServiceReference1.GetUsersResponse retVal = ((WebApplication2.ServiceReference1.userServiceSoap)(this)).GetUsers(inValue);
            return retVal.Body.GetUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.GetUsersResponse> WebApplication2.ServiceReference1.userServiceSoap.GetUsersAsync(WebApplication2.ServiceReference1.GetUsersRequest request) {
            return base.Channel.GetUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication2.ServiceReference1.GetUsersResponse> GetUsersAsync() {
            WebApplication2.ServiceReference1.GetUsersRequest inValue = new WebApplication2.ServiceReference1.GetUsersRequest();
            inValue.Body = new WebApplication2.ServiceReference1.GetUsersRequestBody();
            return ((WebApplication2.ServiceReference1.userServiceSoap)(this)).GetUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.ServiceReference1.GetAdminsResponse WebApplication2.ServiceReference1.userServiceSoap.GetAdmins(WebApplication2.ServiceReference1.GetAdminsRequest request) {
            return base.Channel.GetAdmins(request);
        }
        
        public WebApplication2.ServiceReference1.User[] GetAdmins() {
            WebApplication2.ServiceReference1.GetAdminsRequest inValue = new WebApplication2.ServiceReference1.GetAdminsRequest();
            inValue.Body = new WebApplication2.ServiceReference1.GetAdminsRequestBody();
            WebApplication2.ServiceReference1.GetAdminsResponse retVal = ((WebApplication2.ServiceReference1.userServiceSoap)(this)).GetAdmins(inValue);
            return retVal.Body.GetAdminsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.GetAdminsResponse> WebApplication2.ServiceReference1.userServiceSoap.GetAdminsAsync(WebApplication2.ServiceReference1.GetAdminsRequest request) {
            return base.Channel.GetAdminsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication2.ServiceReference1.GetAdminsResponse> GetAdminsAsync() {
            WebApplication2.ServiceReference1.GetAdminsRequest inValue = new WebApplication2.ServiceReference1.GetAdminsRequest();
            inValue.Body = new WebApplication2.ServiceReference1.GetAdminsRequestBody();
            return ((WebApplication2.ServiceReference1.userServiceSoap)(this)).GetAdminsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.ServiceReference1.GetRegularUsersResponse WebApplication2.ServiceReference1.userServiceSoap.GetRegularUsers(WebApplication2.ServiceReference1.GetRegularUsersRequest request) {
            return base.Channel.GetRegularUsers(request);
        }
        
        public WebApplication2.ServiceReference1.User[] GetRegularUsers() {
            WebApplication2.ServiceReference1.GetRegularUsersRequest inValue = new WebApplication2.ServiceReference1.GetRegularUsersRequest();
            inValue.Body = new WebApplication2.ServiceReference1.GetRegularUsersRequestBody();
            WebApplication2.ServiceReference1.GetRegularUsersResponse retVal = ((WebApplication2.ServiceReference1.userServiceSoap)(this)).GetRegularUsers(inValue);
            return retVal.Body.GetRegularUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.GetRegularUsersResponse> WebApplication2.ServiceReference1.userServiceSoap.GetRegularUsersAsync(WebApplication2.ServiceReference1.GetRegularUsersRequest request) {
            return base.Channel.GetRegularUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication2.ServiceReference1.GetRegularUsersResponse> GetRegularUsersAsync() {
            WebApplication2.ServiceReference1.GetRegularUsersRequest inValue = new WebApplication2.ServiceReference1.GetRegularUsersRequest();
            inValue.Body = new WebApplication2.ServiceReference1.GetRegularUsersRequestBody();
            return ((WebApplication2.ServiceReference1.userServiceSoap)(this)).GetRegularUsersAsync(inValue);
        }
    }
}
